[project]
name = "UniSync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client>=2.200.0",
    "google-auth-httplib2>=0.4.2",
    "google-auth-oauthlib>=1.4.1",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
unisync = "unisync:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.lint]
select = ["E", "F"]
